### PR TITLE
Version Bump in package-lock

### PR DESCRIPTION
**Pull request by Boomatang**
Bump the version in the package-lock.json to match version in package.json.
Added newline to end of package.json to stop scan errors with external build tools.

### CODE REVIEW

**Comment by ziccardi** [comment]
👍  Good catch! We have to update the version bump workflow to update the package-lock.json file too

**Comment by Boomatang** [comment]
@ziccardi Is the updating of the workflow something I should also be doing. Hope not, never done anything with them before. And the coverage reporter seem to be having an issue, I don't think its due to my change.

**Comment by secondsun** [comment]
@Boomatang I think coveralls is fine, it may be running from your github settings instead of the aerogear github settings and thus doesn't see the coveralls key.

**Comment by ziccardi** [comment]
@secondsun @Boomatang Fixed the workflow replacing the `pull_request` event with `pull_request_target`.

**Comment by ziccardi** [comment]
@Boomatang @secondsun This change was requested because the source clear analyser is running `npm install` on the sources. and since `npm install` _'adds the newline in then if I try do scans a second time it says there is uncommitted changes. and fails.'_

However, adding a newline isn't actually a viable solution, since our workflow remove it when the version get bumped (see this [commit](https://github.com/aerogear/unifiedpush-admin-client/commit/53021564dbf46b9a2e696623b7894af3406002cf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)).

The issue, however is that sourceclear is running the wrong command: instead of `npm install` it should run `npm ci` (that doesn't change **any** file: see [here](https://docs.npmjs.com/cli/ci.html#description)).

**Pull request closed without merging**
